repo_url = "https://benzjeremy.github.io/myfdroid/repo"
repo_name = "MyFDroid Repository"
repo_description = "F-Droid Repository for P2P Secure Messenger and Apps."
keystore = "keystore.p12"
repo_keyalias = "fdroid"
keyalias = "fdroid"
keystorepass = "SUPER_SECRET_PASSWORD"
keypass = "SUPER_SECRET_PASSWORD"
