repo_url = "https://benzjeremy.github.io/myfdroid/repo"
repo_name = "Automated Custom F-Droid Repo"
repo_description = "Automatically built and deployed via GitHub Actions."
keystore = "keystore.p12"
repo_keyalias = "fdroid"
keyalias = "fdroid"
keystorepass = "SUPER_SECRET_PASSWORD"
keypass = "SUPER_SECRET_PASSWORD"
